### ISSUE TITLE
curly tx and apidocs should use example value for path parameters, then generated

### ISSUE THREAD

**Issue by rossputin** [passivsystems/protean#105]
we currently hardcode to 1

**Comment by colin-passiv** [comment]
update - path paramters are generated (unless is defined as :gen false, in which case appears as a placeholder).
Do we have a mechanism to define example values? Or is the ticket requesting one, not just the application of it's value?

**Comment by rossputin** [comment]
In the earliest versions of Protean we did have example values, they just got lost somewhere along the way (or perhaps are still lurking but forgotten).  I still see value in the idea.

**Comment by colin-passiv** [comment]
We already had `:vars {:examples [...] }` where first example is used to fill in placeholders. Only generated values took precedence.
I've reordered this now.

**Comment by rossputin** [comment]
I suspected it was in there somewhere, nice one, thanks.
