### ISSUE TITLE
add content type specification in organisational prefs mechanism for sim extensions

### ISSUE THREAD

**Issue by rossputin** [passivsystems/protean#111]
we can currently inspect a request or set a default of JSON in the code, we need this to be configurable in data

**Comment by rossputin** [comment]
more complex parsing required... space after semicolon, case sensitivity etc

**Comment by colin-passiv** [comment]
Content header qualifiers are now optional - though if present, they must match.
To make them mandatory, use environment variable flag: `HDR_QLFS_OPTIONAL=n`
