### ISSUE TITLE
apidocs - child :vars are not displayed in Parameters section

### ISSUE THREAD

**Issue by Shnick** [passivsystems/protean#118]
E.G. Event Type is not mentioned in params section. It is however generating a value in the Curl command.

          :types {
            :EventType "(constrained|query|unchanged)"
          }
          :vars {
            "eventType" {:type :EventType :doc "The event type"}
          }
          :body {
            "id" "1"
            "name" "name"
            "intervalEvents" [
              {"startDateTime" "2014-10-23T07:18:23Z" "value" 1.234 "type" "${eventType}"}
            ]
          }

**Comment by rossputin** [comment]
:body (inline specification) is deprecated now... _but_ the schema will not document query-param types etc, just request body structure

**Comment by rossputin** [comment]
obsolete, will check if a ticket exists for type information on query and form etc params in apidocs
