### ISSUE TITLE
remove prettyprint on curly transformation output - it mangles terminal

### ISSUE THREAD

**Issue by rossputin** [passivsystems/protean#121]

**Comment by rossputin** [comment]
maybe better to make this configurable... via defaults.edn ?  prefer not to have too many config mechanisms

**Comment by colin-passiv** [comment]
Prefer not to put it in defaults.edn since it is a user's preference, not API related. Maybe a user_pref.edn in protean home?

**Comment by Shnick** [comment]
We are not using prettyprint. We are reading a file and do not alter the format.

**Comment by colin-passiv** [comment]
Can we change -v to -i in the generated curl? Don't usually need that level of output.

**Comment by rossputin** [comment]
Hey, thats a separate issue :-)  I'll raise as a new ticket.

**Comment by Shnick** [comment]
By default we flatten to change - export PROTEAN_CURL_FLATTEN='no' 

Case insensitive any of these values will also flatten ["on" "true" "yes" "y"]

**Comment by rossputin** [comment]
Nice one.  Guess we need to update/create some docs for this... (and many other things).
