### ISSUE TITLE
handle graphviz dependency

### ISSUE THREAD

**Issue by rossputin** [passivsystems/protean#137]
we currently need to comment out the image generation on clean installs as graphviz may not be present on the system

**Comment by rossputin** [comment]
Hi Colin... we had some thoughts on this last week... I must admit I forgot what they were... can you see if you can dredge them up and put them in a comment ?  Ta.

**Comment by barriem** [comment]
Yeah Colin, give us your thoughts.

kthxbai

----------------------------------
http://www.bheap.co.uk <http://www.bheap.co.uk/>

Registration Number: 07510939
Registered in England and Wales
