### ISSUE TITLE
SIM - Content-Type must be specified to see request body

### ISSUE THREAD

**Issue by Shnick** [passivsystems/protean#142]
Not sure if this is a bug, maybe worth noting, Content-Type must exist to get a value for (:body _request_)

**Comment by rossputin** [comment]
could be a curl issue

**Comment by colin-passiv** [comment]
I'm tempted to close this issue.
I expect it's clj-ring's behaviour. Although [HTTP spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.2.1) says content-type should be assumed to be binary if not specified, it's common behaviour on servers to return as empty.
