### ISSUE TITLE
Charset parmeter on content-type header should not be mandatory

### ISSUE THREAD

**Issue by Shnick** [passivsystems/protean#143]

**Comment by colin-yell** [comment]
The expected content-type is set in the codex (explicitly or via imports - :content-type or :default-content-type). If it contains a charset refinement, then it is required.

Apart from just removing the charset from the codex (and then expecting clients to never send it), an improvement for Protean would be to support multiple content-types. E.g. both "application/json; charset=utf-8", "application/json" would be acceptable (any other charset would not be).

**Comment by rossputin** [comment]
see #111

**Comment by colin-passiv** [comment]
Closing, since fixed by #111
