### ISSUE TITLE
body-example is asymetric - only an array for responses.

### ISSUE THREAD

**Issue by colin-yell** [passivsystems/protean#144]
It should allow documenting multiple body-examples for requests too.

**Comment by rossputin** [comment]
I've not thought too hard about it... and it is around 30 degrees in this office right now so I am not sure I can, but can anyone think of good use cases for this ?

**Comment by colin-passiv** [comment]
I think it's the same argument for multiple example requests - there may be variations in the resource identified by the endpoint, which we may want to document. The lack of symmetry is only confusing.

**Comment by colin-passiv** [comment]
However, I haven't thought much about the implication on sim-ing. Allow sim extensions to specify which example to return, but default to first example?

**Comment by rossputin** [comment]
I totally agree on the symmetry :-)  It is surprising, which is not good,

**Comment by barriem** [comment]
I like surprises sweetie

**Comment by rossputin** [comment]
I guess sim extensions would be overriding to form their own responses anyhow... so where there is no sim extension we could just randomly select our of the set of responses as per other similar functionality ?
