### ISSUE TITLE
improve service-usage output format

### ISSUE THREAD

**Issue by rossputin** [passivsystems/protean#145]
it is hard to choose a curl command when pretty-print formatting is applied to a list of options, would benefit from blank line between each item

**Comment by barriem** [comment]
or just bumble them and allow the user to pick a number to execute automatically?

**Comment by rossputin** [comment]
Yes, had thought that could be an option... trouble is we generate many values.. and these often cannot be submitted in a request... they serve more as examples.

Could there be an interim edit option ?

**Comment by barriem** [comment]
Maybe split them into two categories? One for examples and one for actual invokable actions?
