### ISSUE TITLE
Improve http response status code tracking

### ISSUE THREAD

**Issue by amlsoft** [passivsystems/protean#147]
Using '>' to track the response status code might be misleading. I would like to suggest 'in' or 'i' instead of '>'

**Comment by rossputin** [comment]
you are right... '>' is misleading...
I'll add '->' to the suggestions... as in '->204'

**Comment by colin-passiv** [comment]
since it is not a transformation (which is implied by ->/to/into etc.), maybe just returning :200 would be clearer - but we would need a way for the caller to handle it (i.e. handle it in a sim-extension, not in the protean framework)

**Comment by Shnick** [comment]
I think it should be (respond 204)

**Comment by rossputin** [comment]
hmmm yes... which anyone could alias to taste in their personal or org sim library...

**Comment by colin-passiv** [comment]
though it's no shorter than {:status 204} which is currently handled? But it's a sim extension choice..

**Comment by amlsoft** [comment]
{:case XXX} is another option though.

**Comment by rossputin** [comment]
if falling back to the lowest level (Ring) map etc we would prefer to stick to {:status XXX}
the problem with this is a typo will not be caught early enough
I think your best bet right now is as per Nick's suggestion... (respond 204) or when we finish re-organising the sim library you can add your own alias for that

does that help for now ?

**Comment by rossputin** [comment]
resolved to taste in personal/organisational sim library
