### ISSUE TITLE
Support query parameter lists

### ISSUE THREAD

**Issue by colin-passiv** [passivsystems/protean#150]
Currently can not indicate in protean where a query parameter can be specified multiple times. e.g.     `?serviceId=1&serviceId=2`

The current method to indicate an optional query parameter is:
`:query-params {:optional {"serviceId" "${serviceId}"}}`
One option would be to invert this to annotate the query param, then we could support additional attributes. E.g.
`:query-params {"serviceId" {"${serviceId}" [:optional :multiple]}}`

**Comment by rossputin** [comment]
How many usecases do we currently have for this ?  I suspect it will involve a large-ish amount of effort.

**Comment by colin-passiv** [comment]
I don't think it will be too bad to implement, but are we happy with the notation?
we could allow either a string (a required value), or a map (value with attributes)
```
:query-params {"username" "${username}"
                          "serviceId" {"${serviceId}" [:optional]}
                          "serviceId" {"${serviceId}" [:optional :multiple]}}
```
any alternative suggestions?

I don't think we have many usecases for this, but it would be nice to settle the codex down earlier.

**Comment by rossputin** [comment]
I find it confusing... too complex.  However no alternatives to suggest at this point.

**Comment by Shnick** [comment]
how about 
```
          :query-params {"status" ["${status}" :optional :multiple]
                         "tags" ["${tags}" :required :single]
  ;;;;;default           "blah" ["{blah}"] 
          }
```

**Comment by colin-passiv** [comment]
I like it.
Same for :form-params?

**Comment by colin-passiv** [comment]
Let's forget about form-params for now - I'm not sure where this sits, since we deprecated other name/value pair usage of body in preference for schema - and this is really a subset of body with content type: application/x-www-form-urlencoded

**Comment by rossputin** [comment]
I've just caught up with Nick on this, I like it.  Sorry for the delay replying on this. +1.
