### ISSUE TITLE
SIM - Generate exception when using "error" function for an undefined status?

### ISSUE THREAD

**Issue by Shnick** [passivsystems/protean#163]
If an error code (e.g. 403) is not defined in the codex, for an endpoint, and you call (error 403) Protean will generate the default success response defined in a codex. I think generating an explicit exception would be safer/better.

**Comment by rossputin** [comment]
would it be acceptable to log a warning rather than throw an error/exception ?  we would currently log a warning if no errors were defined and we had selected one in a sim extension
