### ISSUE TITLE
generated doc should indicate which params are optional

### ISSUE THREAD

**Issue by colin-passiv** [passivsystems/protean#168]
optional and required parameters are just listed together in generated html docs.

**Comment by colin-passiv** [comment]
This should probably wait until we decide what to do with #150 
Other missing param infomation is :examples.

**Comment by rossputin** [comment]
The dreaded #150... still no ideas on that from me.

**Comment by colin-passiv** [comment]
ok, i've spun `:attr [:optional]` out with the parameters. Someone with silky skill can pick it up from there ;)
the attr generation should simplify once we resolve #150

**Comment by Shnick** [comment]
Done - see petstore/api/pet  .... table displays as seen below.

```
Parameters
status 	:Status 	Updated status of the pet 	:optional
```
skillz
