### ISSUE TITLE
Extra hints for protean tests

### ISSUE THREAD

**Issue by colin-passiv** [passivsystems/protean#171]
In practice, it can be difficult for protean to successfully hit all the endpoints of an API, and test they work ok.
To avoid loosing all value, it may be nice to exclude a few problematic endpoints, that way we can at least cover all the simple ones. E.g.
``protean test -f ... - b '{"exclude":[{"get": "my/problematic/endpoint"}]``

Other useful hints, are endpoint ordering, where there is not enough information in the codex to determine the proper ordering. E.g.
``protean test -f ... -b '{"order":[{"get": "hitmefirst/endpoint"}, {"get": "hitmelater/endpoint"}]``
the order endpoint are hit can still be random, but it will add an implicit dependency between these endpoints.

**Comment by rossputin** [comment]
I can see the value in excludes, it may not be possible to calculate how to call an endpoint.

I always figured calculating a graph would mean we do not need to impose order - which always makes me think there is a deeper problem.

**Comment by colin-passiv** [comment]
I agree that there often is a deeper problem in the API design, that should be resolved. But often these deeper problems are inherent in the business logic, or the *non-standard REST* API may already be defined. So rather than just exclude all related endpoints, we should still be able to test the endpoints via an order hint.

**Comment by colin-passiv** [comment]
Added excludes on branch *extract_response_vars*.
The extra parameter looks like: "excludes": [["svc", "method", "path"], ["svc", "method", "path"]]

we may want an alternative to the -b input which takes a json file location, instead of providing a lot of information on the command line

**Comment by colin-passiv** [comment]
Added ordering on branch *extract_response_vars*
Parameter:
```
"order":[[["svc","method1","path1"],["svc","method2","path2"]]]
```
or for multiple:
```
"order":[[["svc","method1","path1"],["svc","method2","path2"]],
         [["svc","method3","path3"],["svc","method3","path3"]]]
```
