### ISSUE TITLE
Support matrix parameters

### ISSUE THREAD

**Issue by colin-passiv** [passivsystems/protean#176]
Since many RESTful APIs use matrix parameters for idiomatic filtering, protean should support them.

**Comment by colin-passiv** [comment]
A possible codex notation could be (using notation proposed in #150):
```
"homes;${homeFilter}/users" {
  :get {
    :req {
      :query-params {"page" ["${page}" :optional]}
      "homeFilter" {"param1" ["${status}" :optional]}
    }
  }
}
```

**Comment by colin-passiv** [comment]
An update on the status of this.

Rolled in updated notation from #150, and included the concept of a **structured** var. This supports the json query-parameter as well as matrix parameters.
e.g.
```
:vars {
  "q" { :type :Json
    :struct {
      "key" ["${gen-me}" :required]
    }
  }
  "filter" { :type :MatrixParams
    :struct {
      "key" ["${gen-me}" :required]
    }
  }
}
```
The generation of vars q/filter will be recursive - also generating gen-me (following all precedence rules of example, bag, generated), and the result formatted according to json/matrix-param format.

Sim has been extended to support querying the matrix parameters of the request.

Outstanding work:
 * the generation of documentation. Currently, I'm documenting all the keys at the "q"/"filter" level, but it should be possible to document the structure keys individually.

* integ test generation. It will generate the whole thing or nothing,  depending on whether the top level ("q"/"filter") is required or not, and level of integ testing. We should respect the optionality of the composing keys.

Additionally, we need to distinguish between matrix-parameters and path-parameters when matching endpoints (they have slightly different matching patterns). It should be possible to identify a matrix-parameter by looking for the type in the codex, however, currently we need the tree for this, and we can't retrieve the tree until we have identified the endpoint.
For now, I am using a special naming convention of matrix-params - they start with ";" - i.e. `";filter"` (reference by `"${;filter}"`) - but hopefully we will remove this requirement.

**Comment by rossputin** [comment]
Good progress, we need to catch up on all this over a curry, when are you guys up for it ?
One thought, is there a simplification we can use in terms of a default for notation ?
Extending into the more sophisticated form when necessary ?
I don't know if I am rambling there or if that makes sense ?

**Comment by colin-passiv** [comment]
Closing this - have opened #177 #178 to cover outstanding work.
