### ISSUE TITLE
Generated docs don't fully reflect body-schema

### ISSUE THREAD

**Issue by memiah-nick** [passivsystems/protean#186]
Within a schema file, if I specify "required" parameters as a subset of declared "properties", the omitted (i.e. optional) parameters are not present within the generated documentation.

**Comment by rossm-memiah** [comment]
Related to #185.

Suggest we read schema in doc-params function, based on extension grab clojure repr of schema and lookup required / optional status in schema repr.

**Comment by rossputin** [comment]
Done
