### ISSUE TITLE
protean home

### ISSUE THREAD

**Issue by colin-passiv** [passivsystems/protean#187]
`document/to-path-dir` looks up resources in the following order:
- `codex-dir`  - the directory where the codex was defined
- `current-dir` - the directory where protean was launched from
- `protean-home` - `env :protean-codex-dir`

I'm unsure about the last one - shouldn't we have an explicit protean-home environment variable?
I think protean-codex-dir is only used for running the server against a multiple codices - but will match codex-dir.

To give context, I want to avoid creating symbolic links in projects to point to the global silk_template - by setting the protean-home environment variable to where this lives - this would be avoided.

**Comment by rossputin** [comment]
Must admit I am not immersed enough to understand this... lets talk it over at the next curry meet up :+1:

**Comment by colin-passiv** [comment]
The environment variable PROTEAN-CODEX-DIR is serving two purposes at the moment.
1) It acts as the "protean home" in the "quantum-lookup" or resources. I.e. serving as defaults if not over-written in current directory or codex directory.
2) It provides the directory for loading codices when running the server.

I will explicitly create a PROTEAN-HOME for the first purpose, leaving the PROTEAN-CODEX-DIR only for the second.
