### ISSUE TITLE
how do we control the order of the floating nav links (table of contents) ?

### ISSUE THREAD

**Issue by rossputin** [passivsystems/protean#188]

**Comment by rossm-memiah** [comment]
We have found through experimentation that by adding 7 endpoints into the sample-perstore.cod.edn (at the time of writing in 'develop' the order of the endpoints in the documentation is incorrect.

Strangely... moving the types and vars blocks above the 'petstore' service into the top level of the codex fixes this problem.

**Comment by rossm-memiah** [comment]
Looks like the issue is a combination of clojure.edn/read-string and our edn (codex structure as mentioned above).

We will dig into the workings of 'read-string' to get a better idea of what is going on.

For not just fix with the codex re-structuring listed above.

**Comment by rossm-memiah** [comment]
Looks like the problem is in clojure 1.6.0 and 1.7.0.

**Comment by Shnick** [comment]
Sort by path and method
