### ISSUE TITLE
Support html in api description in docs

### ISSUE THREAD

**Issue by colin-passiv** [passivsystems/protean#190]
I would like to embed links to external resources in the api description (e.g. to api specifications).
I think by handling html in general, it would be useful to be able to use fonts/bullets etc.

**Comment by rossputin** [comment]
Keen to see how this would look... might we need to support other formats in addition to HTML ?

**Comment by colin-passiv** [comment]
I had thought maybe just to support markdown

**Comment by Shnick** [comment]
supporting markdown in :doc field and dropped :description field
