### ISSUE TITLE
Improve query param documentation

### ISSUE THREAD

**Issue by colin-passiv** [passivsystems/protean#196]
Currently we only document the placeholders in the Parameters section of docs.
These are often interpreted as the query parameters, and if the placeholder and query param names do not match, causes confusion.
I think we're missing a query parameter section, which can also include whether they are optional or not. Also, some query params may have fixed values and would only be seen in curl examples.

e.g.

```
:query-params {
  "token"           ["${bearerToken}" :required]
  "token_type_hint" ["${tokenType}"   :optional]
  "client_id"       ["${clientId}"    :optional]}
```

would document bearerToken, tokenType, clientId which are not valid query parameter names.

**Comment by rossputin** [comment]
Is this mitigated enough by a related ticket #165 ?
