### ISSUE TITLE
3xx response codes are reported as errors

### ISSUE THREAD

**Issue by colin-passiv** [passivsystems/protean#204]
All non 2xx response codes are displayed as errors in generated docs. Only 4xx and 5xx should be considered such.
This also affects default sim behaviour.

**Comment by colin-passiv** [comment]
My issue can be resolved by adjusting the success-status and error-status in protean.core.codex.document.clj:
```
(defn success-status [tree] (status-matching tree #"[123]\d\d"))
(defn error-status [tree] (status-matching tree #"[45]\d\d"))
```
However I'm unsure if this is not ideal for everyone. Is there a reason why 1xx,3xx were considered as errors?Are there cases where we want special treatment for them?

**Comment by rossputin** [comment]
I can't think of any cases where we want special treatment... I suggest this was just not fully implemented.  Come to think of it, I think we played in a world where there were only ever 2xx, 4xx, 5xx codes.
