### ISSUE TITLE
Deactivate schema link when schema is N/A

### ISSUE THREAD

**Issue by Shnick** [passivsystems/protean#214]

**Comment by rossputin** [comment]
I had a couple of reviewers on my current project (devs) comment on removing the schema and example body links wherever they are not applicable... saving vertical space.

So this has popped up a few times now.

Low priority I guess.

**Comment by Shnick** [comment]
Currently the markup looks like this.
```html
<h4>Schema</h4>
<a data-toggle="modal" data-sw-href="#req-body-schema-id" data-sw-text="req-body-schema-title">N/A</a>
<div class="modal">
   ....
</div>
```
We could implement a new Silk attribute which restricts mark up. E.g `data-sw-when`
```html
<div data-sw-when="req-body-schema-title">
  <h4>Schema</h4>
  <a data-toggle="modal" data-sw-href="#req-body-schema-id" data-sw-text="req-body-schema-title" />
  <div class="modal">
    ....
  </div>
</div>
```
And `data-sw-when-not` for disabled link.

Or we could parse the page with JavaScript and disable/hide any links with text N/A.

Or possibly with CSS `a:empty {...}`
