### ISSUE TITLE
Docs: modal for body examples with "." in the name do not open

### ISSUE THREAD

**Issue by colin-passiv** [passivsystems/protean#250]
A body example with a name like "event.post.json" will not be opened by modal in the generated docs. Renaming the file to "event-post.json" is fine.

Looks like there isn't a problem with the schema modals, since the file name is renamed during generation.

**Comment by Shnick** [comment]
Fixed. Modal IDs aren't generated from filename. Using the vector index plus name-spacing for the ID so should be more robust.
