### ISSUE TITLE
Suppress log of returned body when binary

### ISSUE THREAD

**Issue by colin-passiv** [passivsystems/protean#256]
Current behaviour of [protean-api sim-rsp](https://github.com/passivsystems/protean-api/blob/1ab771512d6f44475c688f4e4e65a3bbd9642d49/src/protean/core.clj#L159) is to log the whole returned body.

I have hit an example where the endpoint is returning a large binary file, and this all gets dumped to the logs.
Wonder if it's worth interrogating the Content-Type header to decide whether to include the body in the log (`"<binary>"` would be sufficient). Current example has Content-Type `/application/x-tgz`.

Other things to consider are: 

- truncate the body if too large (sim endpoint may be generating enormous payloads on the fly).
- only dump the body at debug level.

**Comment by Shnick** [comment]
I've moved this log out of protean-api and into the protean project.

Only these body formats TXT, HTML, XML & JSON are written to the log. Any other content is displayed as `"<suppressed>"`. Assuming that the body exists.
