### ISSUE TITLE
Wrong path given to Silk if a data directory occurs before the Silk project directory.

### ISSUE THREAD

**Issue by Shnick** [passivsystems/protean#95]
"~/ " will be feed to Silk in the following example. Should be "~/data/my-silk-project/"

protean visit -f ~/my-project/my-project.cod.edn -b '{"locs":["my-project"], "commands":["doc"],"directory":"~/data/my-silk-project/data/my-project-api"}'

Might have to rework this Protean command. Maybe specifying /data/my-project-api is unnecessary?

**Comment by colin-yell** [comment]
directory option has been removed from doc command - docs will be generated into target - as specified in PROTEAN_TARGET env var, or in current dir.
